### ISSUE TITLE
Is it possible to specify a remote path to sync?

### ISSUE THREAD

**Issue by adempewolff** [cjnaz/RCloneSync#3]
Thanks for your work on this.  Rclone looks like it will be perfect for my needs, so I was excited to see someone working on a bi-directional algorithm.

I have several very large folders shared with me on box and would like to sync just a few specific sub-folders rather than my entire root directory.

If I try doing this, a la:

`python RCloneSync.py --FirstSync --DryRun "remote:Test Box Sync" /home/austin/TestBoxSync`

I get:

`RCloneSync.py: error: argument Cloud: invalid choice: 'remote:Test Box Sync' (choose from 'remote:')`

Suggesting this is not currently implemented.  Am I missing something?  If not, is this a feature that might be added in the future?

Thanks!
Austin

**Comment by cjnaz** [comment]
Hum.  That should be a minor change.  I'll look into it.  Give me a week or
two.  You're welcome to make the edits and post a pull request.
Cin

On Nov 5, 2017 12:04 PM, "Austin Dempewolff" <notifications@github.com>
wrote:

Thanks for your work on this. Rclone looks like it will be perfect for my
needs, so I was excited to see someone working on a bi-directional
algorithm.

I have several very large folders shared with me on box and would like to
sync just a few specific sub-folders rather than my entire root directory.

If I try doing this, a la:

python RCloneSync.py --FirstSync --DryRun "remote:Test Box Sync"
/home/austin/TestBoxSync

I get:

RCloneSync.py: error: argument Cloud: invalid choice: 'remote:Test Box
Sync' (choose from 'remote:')

Suggesting this is not currently implemented. Am I missing something? If
not, is this a feature that might be added in the future?

Thanks!
Austin

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cjnaz/RCloneSync/issues/3>, or mute the thread

**Comment by adempewolff** [comment]
Hi Cin,

Thanks for the quick response!  I haven't used python in a long time (~10 years), but if I have some time to review it in the near future and you haven't had a chance to look at it, I might take a swipe at the edits.

It seems like the basic implementation would be to gather everything in the `cloud` argument, split it into `remoteName` and `remotePath`, then add `remotePath` between `remoteName` and key when building the `src` strings.  That said, I'm not confident enough with my programming ability to try modifying your lovely code with my sloppy hacks without some serious python review beforehand...

Best,
Austin

**Comment by cjnaz** [comment]
That's along the lines I was thinking.  Lots of point edits needed, such as
the naming of the lsl tracking file names.  I'll look at generisizing it to
support two remotes with paths.   Currently I'm working on fixing the error
handling to address a crash related to the remote being offline.

**Comment by desimaniac** [comment]
I am also interested in this feature.

**Comment by cjnaz** [comment]
FYI, I've been working on some cleanup issues primarily related to error handling.  I've looked at the remote path-part feature and I think the change may be straight forward.  I think I'll post the current refresh and then work on the remote path feature.

**Comment by cjnaz** [comment]
Path references on the Cloud argument are now supported.  A fair amount of the code had to be touched for how I was dealing with src and dest paths on the rclone operations.  Also, the LSL filenaming in ~/.RCloneSyncWD/ is changed.  Deleted any older tracking LSL files and do a --FirstSync to get started.  Success?
