### ISSUE TITLE
What's the best handling for a file changed to an older timestamp?

### ISSUE THREAD

**Issue by cjnaz** [cjnaz/RCloneSync#5]
Currently (Nov'17), if a file is changed to an older timestamp on the local system then the older file survives, but if an older file is placed on the remote system then the newer (last sync'd) version on the local system survives again.  Inconsistent handling at least.  

An older file showing up is a hazard at some level, but may have been intentional, such as reverting to a prior version.

**Older file shows up on remote, no change on local**

Solution 1: << Current behavior
- Retain newer local version (Local newer version overwrites remote older, older on remote is lost)

Solution 2:
- Rename local to _LOCAL_NEWER
- Copy remote to local (un-renamed)
- Final `rclone sync` makes both local and remote the same

Solution 3:
- Copy remote to local as _REMOTE_OLDER
- Retain newer local version
- Final `rclone sync` makes both local and remote the same

**Comment by adempewolff** [comment]
Given that I can't imagine this happens all that often, my personal preference would be for it to skip syncing this file and throw a warning and/or require some sort of manual intervention.  Maybe something like a) throw an error and need to be rerun with some sort of force flag or b) throw an interactive prompt asking whether to keep local, remote or skip.

My rational is that a corner case like this is either going to be intentional or something weird that the user wouldn't be likely to notice.  In the former case, the user probably has a very specific aim in mind (and this isn't necessarily going to be the same every time).  In the latter case, it would be nice to actually alert the user to the problem rather than creating a renamed file that they might not notice.

This of course assumes the user is running the program manually rather than as a cron job.  If it's being run automatically, then it becomes more difficult to get the user's attention.  Perhaps the interactive prompt mentioned above with a countdown timer which defaults to skipping on 0.

**Comment by cjnaz** [comment]
No changes implemented yet for this issue.  I use it from a cron job, seldom interactively.  My preference would be Solution 2.  Basically, the change to older survives, and the version on the other system is renamed to _NEWER.  This might suck if a huge dir tree is replaced with an older snapshot, then there may be thousands of files duplicated.  Cleanup might be to `rm *_NEWER`.  Needs more thought.

**Comment by hildogjr** [comment]
If I remember, DropBox utility uses  Solution 2 and give balloon message in its icon (clock to clock).

**Comment by cjnaz** [comment]
Moved to (re-opened in) [V2 repo](https://github.com/cjnaz/rclonesync-V2/issues/3).  See new proposed solution.  Comments (over there) please.
